config/routes.rb
EkiTouch::Application.routes.draw do
  resources :touches
  match 'touchhistory' => 'touches#history'

  resources :stations

  match 'nearstations' => 'near_station#find'
  match 'neareststation' => 'near_station#findnearest'

  match 'registstations' => 'regist_bulk_stations#create'

  

end

app/models/station.rb
class Station < ActiveRecord::Base
  attr_accessible :f_flag, :lat, :line_cd, :line_name, :line_sort, :lon, :pref_cd, :r_type, :rr_cd, :rr_name, :station_cd, :station_g_cd, :station_name, :station_sort
  attr_accessor :distance
  
  has_many :touches
  
  def as_json(options={})
    json = super(options)
    json['distance'] = self.distance
    json
  end  
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stations }
    end
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
    @station = Station.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @station }
    end
  end

  # GET /stations/new
  # GET /stations/new.json
  def new
    @station = Station.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @station }
    end
  end

  # GET /stations/1/edit
  def edit
    @station = Station.find(params[:id])
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(params[:station])

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render json: @station, status: :created, location: @station }
      else
        format.html { render action: "new" }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stations/1
  # PUT /stations/1.json
  def update
    @station = Station.find(params[:id])

    respond_to do |format|
      if @station.update_attributes(params[:station])
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station = Station.find(params[:id])
    @station.destroy

    respond_to do |format|
      format.html { redirect_to stations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rr_cd %><br />
    <%= f.number_field :rr_cd %>
  </div>
  <div class="field">
    <%= f.label :line_cd %><br />
    <%= f.number_field :line_cd %>
  </div>
  <div class="field">
    <%= f.label :station_cd %><br />
    <%= f.number_field :station_cd %>
  </div>
  <div class="field">
    <%= f.label :line_sort %><br />
    <%= f.number_field :line_sort %>
  </div>
  <div class="field">
    <%= f.label :station_sort %><br />
    <%= f.number_field :station_sort %>
  </div>
  <div class="field">
    <%= f.label :station_g_cd %><br />
    <%= f.number_field :station_g_cd %>
  </div>
  <div class="field">
    <%= f.label :r_type %><br />
    <%= f.number_field :r_type %>
  </div>
  <div class="field">
    <%= f.label :rr_name %><br />
    <%= f.text_field :rr_name %>
  </div>
  <div class="field">
    <%= f.label :line_name %><br />
    <%= f.text_field :line_name %>
  </div>
  <div class="field">
    <%= f.label :station_name %><br />
    <%= f.text_field :station_name %>
  </div>
  <div class="field">
    <%= f.label :pref_cd %><br />
    <%= f.number_field :pref_cd %>
  </div>
  <div class="field">
    <%= f.label :lon %><br />
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :f_flag %><br />
    <%= f.number_field :f_flag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<h1>Listing stations</h1>

<table>
  <tr>
    <th>Rr cd</th>
    <th>Line cd</th>
    <th>Station cd</th>
    <th>Line sort</th>
    <th>Station sort</th>
    <th>Station g cd</th>
    <th>R type</th>
    <th>Rr name</th>
    <th>Line name</th>
    <th>Station name</th>
    <th>Pref cd</th>
    <th>Lon</th>
    <th>Lat</th>
    <th>F flag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stations.each do |station| %>
  <tr>
    <td><%= station.rr_cd %></td>
    <td><%= station.line_cd %></td>
    <td><%= station.station_cd %></td>
    <td><%= station.line_sort %></td>
    <td><%= station.station_sort %></td>
    <td><%= station.station_g_cd %></td>
    <td><%= station.r_type %></td>
    <td><%= station.rr_name %></td>
    <td><%= station.line_name %></td>
    <td><%= station.station_name %></td>
    <td><%= station.pref_cd %></td>
    <td><%= station.lon %></td>
    <td><%= station.lat %></td>
    <td><%= station.f_flag %></td>
    <td><%= link_to 'Show', station %></td>
    <td><%= link_to 'Edit', edit_station_path(station) %></td>
    <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New station</h1>

<%= render 'form' %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rr cd:</b>
  <%= @station.rr_cd %>
</p>

<p>
  <b>Line cd:</b>
  <%= @station.line_cd %>
</p>

<p>
  <b>Station cd:</b>
  <%= @station.station_cd %>
</p>

<p>
  <b>Line sort:</b>
  <%= @station.line_sort %>
</p>

<p>
  <b>Station sort:</b>
  <%= @station.station_sort %>
</p>

<p>
  <b>Station g cd:</b>
  <%= @station.station_g_cd %>
</p>

<p>
  <b>R type:</b>
  <%= @station.r_type %>
</p>

<p>
  <b>Rr name:</b>
  <%= @station.rr_name %>
</p>

<p>
  <b>Line name:</b>
  <%= @station.line_name %>
</p>

<p>
  <b>Station name:</b>
  <%= @station.station_name %>
</p>

<p>
  <b>Pref cd:</b>
  <%= @station.pref_cd %>
</p>

<p>
  <b>Lon:</b>
  <%= @station.lon %>
</p>

<p>
  <b>Lat:</b>
  <%= @station.lat %>
</p>

<p>
  <b>F flag:</b>
  <%= @station.f_flag %>
</p>


<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>