config/routes.rb
EkiTouch::Application.routes.draw do
  resources :touches
  match 'touchhistory' => 'touches#history'

  resources :stations

  match 'nearstations' => 'near_station#find'
  match 'neareststation' => 'near_station#findnearest'

  match 'registstations' => 'regist_bulk_stations#create'

  

end

app/models/touch.rb
class Touch < ActiveRecord::Base
  attr_accessible :station_id, :touched_date, :user_id
  
  belongs_to :station
  
end

app/controllers/touches_controller.rb
class TouchesController < ApplicationController
  # GET /touches
  # GET /touches.json
  def index
    @touches = Touch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @touches }
    end
  end

  def history
    user_id = params[:user_id]
    
    touch = Touch.find(:all, 
      :order => "touched_date desc", 
      :conditions => ["user_id = ?", user_id], 
      :include => :station
    )
    
    render :json => touch.to_json(:include => :station) 
  end

  # GET /touches/1
  # GET /touches/1.json
  def show
    @touch = Touch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @touch }
    end
  end

  # GET /touches/new
  # GET /touches/new.json
  def new
    @touch = Touch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @touch }
    end
  end

  # GET /touches/1/edit
  def edit
    @touch = Touch.find(params[:id])
  end

  # POST /touches
  # POST /touches.json
  def create
    @touch = Touch.new(params[:touch])

    respond_to do |format|
      if @touch.save
        format.html { redirect_to @touch, notice: 'Touch was successfully created.' }
        format.json { render json: @touch, status: :created, location: @touch }
      else
        format.html { render action: "new" }
        format.json { render json: @touch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /touches/1
  # PUT /touches/1.json
  def update
    @touch = Touch.find(params[:id])

    respond_to do |format|
      if @touch.update_attributes(params[:touch])
        format.html { redirect_to @touch, notice: 'Touch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @touch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /touches/1
  # DELETE /touches/1.json
  def destroy
    @touch = Touch.find(params[:id])
    @touch.destroy

    respond_to do |format|
      format.html { redirect_to touches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/touches_helper.rb
module TouchesHelper
end

app/views/touches/_form.html.erb
<%= form_for(@touch) do |f| %>
  <% if @touch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@touch.errors.count, "error") %> prohibited this touch from being saved:</h2>

      <ul>
      <% @touch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :station_id %><br />
    <%= f.number_field :station_id %>
  </div>
  <div class="field">
    <%= f.label :touched_date %><br />
    <%= f.datetime_select :touched_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/touches/edit.html.erb
<h1>Editing touch</h1>

<%= render 'form' %>

<%= link_to 'Show', @touch %> |
<%= link_to 'Back', touches_path %>

app/views/touches/index.html.erb
<h1>Listing touches</h1>

<table>
  <tr>
    <th>User</th>
    <th>Station</th>
    <th>Touched date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @touches.each do |touch| %>
  <tr>
    <td><%= touch.user_id %></td>
    <td><%= touch.station_id %></td>
    <td><%= touch.touched_date %></td>
    <td><%= link_to 'Show', touch %></td>
    <td><%= link_to 'Edit', edit_touch_path(touch) %></td>
    <td><%= link_to 'Destroy', touch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Touch', new_touch_path %>

app/views/touches/new.html.erb
<h1>New touch</h1>

<%= render 'form' %>

<%= link_to 'Back', touches_path %>

app/views/touches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @touch.user_id %>
</p>

<p>
  <b>Station:</b>
  <%= @touch.station_id %>
</p>

<p>
  <b>Touched date:</b>
  <%= @touch.touched_date %>
</p>


<%= link_to 'Edit', edit_touch_path(@touch) %> |
<%= link_to 'Back', touches_path %>